# Generated by Django 6.0.1 on 2026-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_failed_payment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='disabled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('read_only', 'Read Only'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
